group 'com.swytchhub.nativevoice'
version '0.1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.swytchhub.nativevoice'
    compileSdk 36

    defaultConfig {
        minSdk 26
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.twilio:voice-android:6.10.2'
    implementation 'com.google.firebase:firebase-messaging:24.1.2'
    implementation 'androidx.core:core:1.15.0'
}
